/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TimesheetRouteImport } from './routes/timesheet'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NonbillableRouteImport } from './routes/nonbillable'
import { Route as MisRouteImport } from './routes/mis'
import { Route as MatterRouteImport } from './routes/matter'
import { Route as MailsRouteImport } from './routes/mails'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CockpitRouteImport } from './routes/cockpit'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsNewRouteImport } from './routes/reports.new'
import { Route as ReportsDrillRouteImport } from './routes/reports.drill'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as NotificationsPreferencesRouteImport } from './routes/notifications.preferences'
import { Route as MisBoardIdRouteImport } from './routes/mis.$boardId'
import { Route as MatterNewRouteImport } from './routes/matter.new'
import { Route as MatterAllocationRouteImport } from './routes/matter.allocation'
import { Route as MatterIdRouteImport } from './routes/matter.$id'
import { Route as MailsAutoLogRouteImport } from './routes/mails.auto-log'
import { Route as MailsIdRouteImport } from './routes/mails.$id'
import { Route as CockpitScopeRouteImport } from './routes/cockpit.scope'
import { Route as CockpitFirmRouteImport } from './routes/cockpit.firm'
import { Route as ClientRequestsRouteImport } from './routes/client.requests'
import { Route as ClientIdRouteImport } from './routes/client.$id'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ReportsIdEditRouteImport } from './routes/reports.$id.edit'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetRoute = TimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NonbillableRoute = NonbillableRouteImport.update({
  id: '/nonbillable',
  path: '/nonbillable',
  getParentRoute: () => rootRouteImport,
} as any)
const MisRoute = MisRouteImport.update({
  id: '/mis',
  path: '/mis',
  getParentRoute: () => rootRouteImport,
} as any)
const MatterRoute = MatterRouteImport.update({
  id: '/matter',
  path: '/matter',
  getParentRoute: () => rootRouteImport,
} as any)
const MailsRoute = MailsRouteImport.update({
  id: '/mails',
  path: '/mails',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CockpitRoute = CockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDrillRoute = ReportsDrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const NotificationsPreferencesRoute =
  NotificationsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => NotificationsRoute,
  } as any)
const MisBoardIdRoute = MisBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => MisRoute,
} as any)
const MatterNewRoute = MatterNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MatterRoute,
} as any)
const MatterAllocationRoute = MatterAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => MatterRoute,
} as any)
const MatterIdRoute = MatterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatterRoute,
} as any)
const MailsAutoLogRoute = MailsAutoLogRouteImport.update({
  id: '/auto-log',
  path: '/auto-log',
  getParentRoute: () => MailsRoute,
} as any)
const MailsIdRoute = MailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MailsRoute,
} as any)
const CockpitScopeRoute = CockpitScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => CockpitRoute,
} as any)
const CockpitFirmRoute = CockpitFirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => CockpitRoute,
} as any)
const ClientRequestsRoute = ClientRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ClientRoute,
} as any)
const ClientIdRoute = ClientIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientRoute,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ReportsIdEditRoute = ReportsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/client': typeof ClientRouteWithChildren
  '/cockpit': typeof CockpitRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/diary': typeof DiaryRoute
  '/login': typeof LoginRoute
  '/mails': typeof MailsRouteWithChildren
  '/matter': typeof MatterRouteWithChildren
  '/mis': typeof MisRouteWithChildren
  '/nonbillable': typeof NonbillableRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRouteWithChildren
  '/timesheet': typeof TimesheetRoute
  '/today': typeof TodayRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/client/$id': typeof ClientIdRoute
  '/client/requests': typeof ClientRequestsRoute
  '/cockpit/firm': typeof CockpitFirmRoute
  '/cockpit/scope': typeof CockpitScopeRoute
  '/mails/$id': typeof MailsIdRoute
  '/mails/auto-log': typeof MailsAutoLogRoute
  '/matter/$id': typeof MatterIdRoute
  '/matter/allocation': typeof MatterAllocationRoute
  '/matter/new': typeof MatterNewRoute
  '/mis/$boardId': typeof MisBoardIdRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/reports/drill': typeof ReportsDrillRoute
  '/reports/new': typeof ReportsNewRoute
  '/reports/$id/edit': typeof ReportsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/client': typeof ClientRouteWithChildren
  '/cockpit': typeof CockpitRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/diary': typeof DiaryRoute
  '/login': typeof LoginRoute
  '/mails': typeof MailsRouteWithChildren
  '/matter': typeof MatterRouteWithChildren
  '/mis': typeof MisRouteWithChildren
  '/nonbillable': typeof NonbillableRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRouteWithChildren
  '/timesheet': typeof TimesheetRoute
  '/today': typeof TodayRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/client/$id': typeof ClientIdRoute
  '/client/requests': typeof ClientRequestsRoute
  '/cockpit/firm': typeof CockpitFirmRoute
  '/cockpit/scope': typeof CockpitScopeRoute
  '/mails/$id': typeof MailsIdRoute
  '/mails/auto-log': typeof MailsAutoLogRoute
  '/matter/$id': typeof MatterIdRoute
  '/matter/allocation': typeof MatterAllocationRoute
  '/matter/new': typeof MatterNewRoute
  '/mis/$boardId': typeof MisBoardIdRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/reports/drill': typeof ReportsDrillRoute
  '/reports/new': typeof ReportsNewRoute
  '/reports/$id/edit': typeof ReportsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/client': typeof ClientRouteWithChildren
  '/cockpit': typeof CockpitRouteWithChildren
  '/collections': typeof CollectionsRoute
  '/compare': typeof CompareRoute
  '/compliance': typeof ComplianceRoute
  '/diary': typeof DiaryRoute
  '/login': typeof LoginRoute
  '/mails': typeof MailsRouteWithChildren
  '/matter': typeof MatterRouteWithChildren
  '/mis': typeof MisRouteWithChildren
  '/nonbillable': typeof NonbillableRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRouteWithChildren
  '/timesheet': typeof TimesheetRoute
  '/today': typeof TodayRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/client/$id': typeof ClientIdRoute
  '/client/requests': typeof ClientRequestsRoute
  '/cockpit/firm': typeof CockpitFirmRoute
  '/cockpit/scope': typeof CockpitScopeRoute
  '/mails/$id': typeof MailsIdRoute
  '/mails/auto-log': typeof MailsAutoLogRoute
  '/matter/$id': typeof MatterIdRoute
  '/matter/allocation': typeof MatterAllocationRoute
  '/matter/new': typeof MatterNewRoute
  '/mis/$boardId': typeof MisBoardIdRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
  '/reports/$id': typeof ReportsIdRouteWithChildren
  '/reports/drill': typeof ReportsDrillRoute
  '/reports/new': typeof ReportsNewRoute
  '/reports/$id/edit': typeof ReportsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approvals'
    | '/client'
    | '/cockpit'
    | '/collections'
    | '/compare'
    | '/compliance'
    | '/diary'
    | '/login'
    | '/mails'
    | '/matter'
    | '/mis'
    | '/nonbillable'
    | '/notifications'
    | '/pipeline'
    | '/reports'
    | '/timesheet'
    | '/today'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/rules'
    | '/client/$id'
    | '/client/requests'
    | '/cockpit/firm'
    | '/cockpit/scope'
    | '/mails/$id'
    | '/mails/auto-log'
    | '/matter/$id'
    | '/matter/allocation'
    | '/matter/new'
    | '/mis/$boardId'
    | '/notifications/preferences'
    | '/reports/$id'
    | '/reports/drill'
    | '/reports/new'
    | '/reports/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approvals'
    | '/client'
    | '/cockpit'
    | '/collections'
    | '/compare'
    | '/compliance'
    | '/diary'
    | '/login'
    | '/mails'
    | '/matter'
    | '/mis'
    | '/nonbillable'
    | '/notifications'
    | '/pipeline'
    | '/reports'
    | '/timesheet'
    | '/today'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/rules'
    | '/client/$id'
    | '/client/requests'
    | '/cockpit/firm'
    | '/cockpit/scope'
    | '/mails/$id'
    | '/mails/auto-log'
    | '/matter/$id'
    | '/matter/allocation'
    | '/matter/new'
    | '/mis/$boardId'
    | '/notifications/preferences'
    | '/reports/$id'
    | '/reports/drill'
    | '/reports/new'
    | '/reports/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approvals'
    | '/client'
    | '/cockpit'
    | '/collections'
    | '/compare'
    | '/compliance'
    | '/diary'
    | '/login'
    | '/mails'
    | '/matter'
    | '/mis'
    | '/nonbillable'
    | '/notifications'
    | '/pipeline'
    | '/reports'
    | '/timesheet'
    | '/today'
    | '/admin/audit'
    | '/admin/roles'
    | '/admin/rules'
    | '/client/$id'
    | '/client/requests'
    | '/cockpit/firm'
    | '/cockpit/scope'
    | '/mails/$id'
    | '/mails/auto-log'
    | '/matter/$id'
    | '/matter/allocation'
    | '/matter/new'
    | '/mis/$boardId'
    | '/notifications/preferences'
    | '/reports/$id'
    | '/reports/drill'
    | '/reports/new'
    | '/reports/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  ClientRoute: typeof ClientRouteWithChildren
  CockpitRoute: typeof CockpitRouteWithChildren
  CollectionsRoute: typeof CollectionsRoute
  CompareRoute: typeof CompareRoute
  ComplianceRoute: typeof ComplianceRoute
  DiaryRoute: typeof DiaryRoute
  LoginRoute: typeof LoginRoute
  MailsRoute: typeof MailsRouteWithChildren
  MatterRoute: typeof MatterRouteWithChildren
  MisRoute: typeof MisRouteWithChildren
  NonbillableRoute: typeof NonbillableRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  PipelineRoute: typeof PipelineRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  TimesheetRoute: typeof TimesheetRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheet': {
      id: '/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof TimesheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nonbillable': {
      id: '/nonbillable'
      path: '/nonbillable'
      fullPath: '/nonbillable'
      preLoaderRoute: typeof NonbillableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis': {
      id: '/mis'
      path: '/mis'
      fullPath: '/mis'
      preLoaderRoute: typeof MisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matter': {
      id: '/matter'
      path: '/matter'
      fullPath: '/matter'
      preLoaderRoute: typeof MatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mails': {
      id: '/mails'
      path: '/mails'
      fullPath: '/mails'
      preLoaderRoute: typeof MailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockpit': {
      id: '/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof CockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/drill': {
      id: '/reports/drill'
      path: '/drill'
      fullPath: '/reports/drill'
      preLoaderRoute: typeof ReportsDrillRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/notifications/preferences': {
      id: '/notifications/preferences'
      path: '/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof NotificationsPreferencesRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/mis/$boardId': {
      id: '/mis/$boardId'
      path: '/$boardId'
      fullPath: '/mis/$boardId'
      preLoaderRoute: typeof MisBoardIdRouteImport
      parentRoute: typeof MisRoute
    }
    '/matter/new': {
      id: '/matter/new'
      path: '/new'
      fullPath: '/matter/new'
      preLoaderRoute: typeof MatterNewRouteImport
      parentRoute: typeof MatterRoute
    }
    '/matter/allocation': {
      id: '/matter/allocation'
      path: '/allocation'
      fullPath: '/matter/allocation'
      preLoaderRoute: typeof MatterAllocationRouteImport
      parentRoute: typeof MatterRoute
    }
    '/matter/$id': {
      id: '/matter/$id'
      path: '/$id'
      fullPath: '/matter/$id'
      preLoaderRoute: typeof MatterIdRouteImport
      parentRoute: typeof MatterRoute
    }
    '/mails/auto-log': {
      id: '/mails/auto-log'
      path: '/auto-log'
      fullPath: '/mails/auto-log'
      preLoaderRoute: typeof MailsAutoLogRouteImport
      parentRoute: typeof MailsRoute
    }
    '/mails/$id': {
      id: '/mails/$id'
      path: '/$id'
      fullPath: '/mails/$id'
      preLoaderRoute: typeof MailsIdRouteImport
      parentRoute: typeof MailsRoute
    }
    '/cockpit/scope': {
      id: '/cockpit/scope'
      path: '/scope'
      fullPath: '/cockpit/scope'
      preLoaderRoute: typeof CockpitScopeRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/cockpit/firm': {
      id: '/cockpit/firm'
      path: '/firm'
      fullPath: '/cockpit/firm'
      preLoaderRoute: typeof CockpitFirmRouteImport
      parentRoute: typeof CockpitRoute
    }
    '/client/requests': {
      id: '/client/requests'
      path: '/requests'
      fullPath: '/client/requests'
      preLoaderRoute: typeof ClientRequestsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/$id': {
      id: '/client/$id'
      path: '/$id'
      fullPath: '/client/$id'
      preLoaderRoute: typeof ClientIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reports/$id/edit': {
      id: '/reports/$id/edit'
      path: '/edit'
      fullPath: '/reports/$id/edit'
      preLoaderRoute: typeof ReportsIdEditRouteImport
      parentRoute: typeof ReportsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminRulesRoute: typeof AdminRulesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminRulesRoute: AdminRulesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientIdRoute: typeof ClientIdRoute
  ClientRequestsRoute: typeof ClientRequestsRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientIdRoute: ClientIdRoute,
  ClientRequestsRoute: ClientRequestsRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface CockpitRouteChildren {
  CockpitFirmRoute: typeof CockpitFirmRoute
  CockpitScopeRoute: typeof CockpitScopeRoute
}

const CockpitRouteChildren: CockpitRouteChildren = {
  CockpitFirmRoute: CockpitFirmRoute,
  CockpitScopeRoute: CockpitScopeRoute,
}

const CockpitRouteWithChildren =
  CockpitRoute._addFileChildren(CockpitRouteChildren)

interface MailsRouteChildren {
  MailsIdRoute: typeof MailsIdRoute
  MailsAutoLogRoute: typeof MailsAutoLogRoute
}

const MailsRouteChildren: MailsRouteChildren = {
  MailsIdRoute: MailsIdRoute,
  MailsAutoLogRoute: MailsAutoLogRoute,
}

const MailsRouteWithChildren = MailsRoute._addFileChildren(MailsRouteChildren)

interface MatterRouteChildren {
  MatterIdRoute: typeof MatterIdRoute
  MatterAllocationRoute: typeof MatterAllocationRoute
  MatterNewRoute: typeof MatterNewRoute
}

const MatterRouteChildren: MatterRouteChildren = {
  MatterIdRoute: MatterIdRoute,
  MatterAllocationRoute: MatterAllocationRoute,
  MatterNewRoute: MatterNewRoute,
}

const MatterRouteWithChildren =
  MatterRoute._addFileChildren(MatterRouteChildren)

interface MisRouteChildren {
  MisBoardIdRoute: typeof MisBoardIdRoute
}

const MisRouteChildren: MisRouteChildren = {
  MisBoardIdRoute: MisBoardIdRoute,
}

const MisRouteWithChildren = MisRoute._addFileChildren(MisRouteChildren)

interface NotificationsRouteChildren {
  NotificationsPreferencesRoute: typeof NotificationsPreferencesRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsPreferencesRoute: NotificationsPreferencesRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface ReportsIdRouteChildren {
  ReportsIdEditRoute: typeof ReportsIdEditRoute
}

const ReportsIdRouteChildren: ReportsIdRouteChildren = {
  ReportsIdEditRoute: ReportsIdEditRoute,
}

const ReportsIdRouteWithChildren = ReportsIdRoute._addFileChildren(
  ReportsIdRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRouteWithChildren
  ReportsDrillRoute: typeof ReportsDrillRoute
  ReportsNewRoute: typeof ReportsNewRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRouteWithChildren,
  ReportsDrillRoute: ReportsDrillRoute,
  ReportsNewRoute: ReportsNewRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  ClientRoute: ClientRouteWithChildren,
  CockpitRoute: CockpitRouteWithChildren,
  CollectionsRoute: CollectionsRoute,
  CompareRoute: CompareRoute,
  ComplianceRoute: ComplianceRoute,
  DiaryRoute: DiaryRoute,
  LoginRoute: LoginRoute,
  MailsRoute: MailsRouteWithChildren,
  MatterRoute: MatterRouteWithChildren,
  MisRoute: MisRouteWithChildren,
  NonbillableRoute: NonbillableRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  PipelineRoute: PipelineRoute,
  ReportsRoute: ReportsRouteWithChildren,
  TimesheetRoute: TimesheetRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
